
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())

# chargement des données 
donnees_mean <- readRDS("data_post_etape_4_Mean.Rdata", "rb")
donnees_mean2 <- donnees_mean[,-1]

```

```{r}
donnees_mean2$y <- relevel(donnees_mean2$y, ref = "ENG_malade")

multinomial_logistic_model <- vglm(y ~ . ,data = donnees_mean2, family = multinomial)


library(MASS)
library(car)
library(caret)

# Suppression des variables non significatives (si nécessaire)
modele_reduit <- vglm(y ~ X09x3_FAB_CROISS_reg_rec +
                        X22x1_LOC_INF_rec +
                        X06x1_gene_majo_1_rec +
                        X12x2_MAT_PC +
                        T10_PS_EauDebi_3 +
                        X07x1_AN_CONST4_mean_3 +
                        LR_LRF +
                        T13_ENG_milieuDegrad.x +
                        X19x2_ABB_E +
                        A03_Pos10sVERS +
                        A03_PosSeroMyAs +
                        A03_TxPosSero22sTgReel, 
                      family = multinomial, data = donnees_mean2)

modele_reduit2 <- vglm(y ~ X09x3_FAB_CROISS_reg_rec +
                        X06x1_gene_majo_1_rec +
                        X12x2_MAT_PC +
                        T10_PS_EauDebi_3 +
                        X07x1_AN_CONST4_mean_3 +
                        LR_LRF +
                        T13_ENG_milieuDegrad.x +
                        A03_Pos10sVERS +
                        A03_PosSeroMyAs +
                        A03_TxPosSero22sTgReel, 
                      family = multinomial, data = donnees_mean2)

modele_reduit3 <- vglm(y ~ X09x3_FAB_CROISS_reg_rec +
                        X06x1_gene_majo_1_rec +
                        X12x2_MAT_PC +
                        T10_PS_EauDebi_3 +
                        X07x1_AN_CONST4_mean_3 +
                        LR_LRF +
                        T13_ENG_milieuDegrad.x +
                        A03_Pos10sVERS +
                        A03_PosSeroMyAs, 
                      family = multinomial, data = donnees_mean2)

summary(multinomial_logistic_model)
summary(modele_reduit)
summary(modele_reduit2)
summary(modele_reduit3)

logLik(multinomial_logistic_model)
logLik(modele_reduit)
logLik(modele_reduit2)
logLik(modele_reduit3)

anova(multinomial_logistic_model)
anova(modele_reduit)
anova(modele_reduit2)
anova(modele_reduit3)

AIC(multinomial_logistic_model)
AIC(modele_reduit)
AIC(modele_reduit2)
AIC(modele_reduit3)

BIC(multinomial_logistic_model)
BIC(modele_reduit)
BIC(modele_reduit2)
BIC(modele_reduit3)



# Ainsi, est-ce que c'est significatif ?



# Calcul de la statistique du test (écart de log-vraisemblance)
logLik_complet <- logLik(multinomial_logistic_model)
logLik_reduit <- logLik(modele_reduit)
logLik_reduit2 <- logLik(modele_reduit2)
logLik_reduit3 <- logLik(modele_reduit3)
X_stat <- -2 * (logLik_reduit - logLik_complet)  # Écart de log-vraisemblance
X_stat2 <- -2 * (logLik_reduit2 - logLik_reduit)  # Écart de log-vraisemblance
X_stat3 <- -2 * (logLik_reduit3 - logLik_reduit2)  # Écart de log-vraisemblance

# Degrés de liberté (différence du nombre de paramètres entre les modèles)
df <- 21 - 12
df2 <- 12 - 10
df3 <- 1

# Calcul de la p-value
p_value <- pchisq(X_stat, df, lower.tail = FALSE)
p_value2 <- pchisq(X_stat2, df2, lower.tail = FALSE)
p_value3 <- pchisq(X_stat3, df3, lower.tail = FALSE)

# Affichage des résultats
cat("Statistique du test X² :", X_stat, X_stat2, X_stat3, "\n")
cat("Degrés de liberté :", df, df2, df3, "\n")
cat("P-value associée :", p_value, p_value2, p_value3, "\n")


levels(donnees_mean2$y)














```




```{r}
# Charger la librairie dplyr si ce n'est pas déjà fait
library(dplyr)

# Supprimer les variables spécifiques de la base de données
donnees_mean <- donnees_mean %>%
  select(-"X07x1_AN_CONST4_mean_3", 
         -"T16_BS_TenueSpeciElev", 
         -"LR_LRF", 
         -"T10_PS_AlimPoNourrLongpPo")

# Vérifier les nouvelles colonnes de la base de données
colnames(donnees_mean)

set.seed(36)
train_index <- createDataPartition(donnees_mean$y, p = 0.8, list = FALSE)
train_data <- donnees_mean[train_index, ]
test_data <- donnees_mean[-train_index, ]

library("VGAM")
multinomial_logistic_model <- vglm(y ~ . ,data = train_data, family = multinomial)
```

```{r}
model_summary <- summary(modele_reduit3)
coefficients <- coefficients(model_summary)

# Utiliser la méthode 'z' pour obtenir les valeurs des statistiques de Wald
wald_statistics <- coefficients[, "z value"]

# Utiliser la méthode 'Pr(>|z|)' pour obtenir les p-values
p_values <- coefficients[, "Pr(>|z|)"]

# Vérifier les p-values
print(p_values)

# Identifier les variables avec des p-values significatives (par exemple p < 0.05)
significant_vars <- names(p_values)[p_values < 0.05]

# Créer une formule avec les variables significatives
formula <- as.formula(paste("y ~", paste(significant_vars, collapse = " + ")))
formula
# Créer un nouveau modèle avec les variables significatives
significant_model <- vglm(y ~ X09x3_FAB_CROISS_reg_rec + 
    X12x2_MAT_PC + T10_PS_EauDebi_3 + 
    X07x1_AN_CONST4_mean_3 + LR_LRF + T13_ENG_milieuDegrad.x + 
    A03_Pos10sVERS + A03_PosSeroMyAs, data = donnees_mean2, family = multinomial())

# Afficher le résumé du nouveau modèle
summary(significant_model)
anova(significant_model)
```


